name: Build & Tests
on: [push, pull_request]
jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_12.4.app
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          targets: aarch64-apple-ios, x86_64-apple-ios, aarch64-apple-darwin, x86_64-apple-darwin
      - name: Installing cargo-lipo
        run: cargo install cargo-lipo
      - name: Building XCFramework
        run: bash scripts/build_binary_macos.sh
      - name: Patching Package.swift for testing
        run: sed -i '' 's/let[[:blank:]]useLocalBinary[[:blank:]]=[[:blank:]]false/let useLocalBinary = true/g' Package.swift
      - name: Build and Test SPM
        run: swift test
      - name: Update Cocoa Pods repo
        run: pod repo update
      - name: Build and Test CocoaPods
        run: pod lib lint --allow-warnings --fail-fast Sr25519.podspec
  linux:
    runs-on: ubuntu-latest
    container:
      image: swift:5.3
      options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --security-opt apparmor=unconfined
    steps:
      - name: Ubuntu Packages
        run: sudo apt-get update && sudo apt-get upgrade -y git && sudo apt-get install -y wget curl
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install wget and curl
        run: sudo apt-get install wget curl
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Building Rust
        run: bash scripts/build_binary_linux.sh binaries
      - name: Build and Test
        run: swift test -Xlinker -Lbinaries/lib -Xcc -Ibinaries/include
