name: Publish CocoaPods package
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_12.4.app
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          targets: ['aarch64-apple-ios', 'x86_64-apple-ios', 'aarch64-apple-darwin' , 'x86_64-apple-darwin']
      - name: Installing cargo-lipo
        run: cargo install cargo-lipo
      - name: Uploading binaries pod if needed
        run: bash scripts/push_binary_pod.sh
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      - name: Update Cocoa Pods repo
        run: pod repo update
      - name: Publish Pod
        run: pod trunk push --allow-warnings Sr25519.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        
